---
services:
  redis:
    image: redis:alpine

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  vote:
    image: voting-app #OR  build: ./vote
    ports:
      - 5000:80
        #    depends_on:
        #      redis:

  worker:
    image: worker-app #OR build: ./worker
      #    depends_on:
      #      redis:
      #      db:

  result:
    image: result-app #OR build: ./result
    ports:
      - 5001:80  
        #    depends_on:
        #      db:
